enum EClientAction {
    NEW_MESSAGE = "NEW_MESSAGE",
    NEW_CONVERSATION_INVITE = "NEW_CONVERSATION_INVITE",
    NEW_CONVERSATION_INVITE_ACK = "NEW_CONVERSATION_ACK"
}

export default EClientAction;